### ISSUE TITLE
SVG does not animate when imported in JS files

### ISSUE THREAD

**Issue by vreddi** [maxwellito/vivus-instant#15]
Browser used: Latest Chrome

I am trying to use the animated SVG within a React application which is bundled using webpack. Webpack config does use the `image-webpack-loader` module which allows me to import the svg in one of my react component files:

```js
import SearchImage from 'assets/images/search_animated.svg';
```
and be used in my React component as JSX:
```js
<img src={SearchImage} alt="" className="searchbox-cover-no-results-image" />
```

When this renders on the browser no animation triggers. The image stays in its initial state.
<img width="201" alt="Screen Shot 2019-04-07 at 12 14 26 PM" src="https://user-images.githubusercontent.com/6148930/55688576-d47f7000-592e-11e9-9baa-376f0ce61326.png">

However when I tried manually adding the image in the html, the animation worked just fine.
<img width="204" alt="Screen Shot 2019-04-07 at 12 14 34 PM" src="https://user-images.githubusercontent.com/6148930/55688578-d9dcba80-592e-11e9-8d76-6e93331a7592.png">

Seems like there might be compatibility issues with how the image is being imported. Any ideas how could I fix this within the React app?

**Comment by maxwellito** [comment]
Hi there,
Do you have the embedded code available somewhere? I believe the `image-webpack-loader` is removing vital parts of the SVG animation. 
Do you have an optimiser as part of your build? 

Maybe try to disable `svgo`

```js
use: [
  'file-loader',
  {
    loader: 'image-webpack-loader',
    options: {
      ...
      svgo: {
        enabled: false
      }
    }
  }
]
```

**Comment by vreddi** [comment]
@maxwellito Yes that makes sense. That worked!
